### PR TITLE
Conditionally clear the agents call object when returning the agent

### PR DESCRIPTION
**Pull request by terryfinn**
We use the agent's state in an Electric Slide Call Queue to build
dashboards that show the agents who are signed in and what calls they
are on. The dashboards all work fine, except when a call queued and
wait for an agent. In these cases, often, we lose the information we
need to know what call the agent is on.

This bug is easiest to replicate with one agent signed in and two
calls get placed simultaneously. One of the two calls will queue, and
the other will go straight to the available agent. The dashboard will
work fine at this point, and we can report what call the agent is
on. When the call ends, the queued call will also go to this agent,
but the dashboard will not have the information needed to report what
call the agent is on.

When we connect an agent to a call, we register a call end
handler. The call end handler will return the agent to make them
available for calls and clear out the agents all. When we return the
agent, we also check to see if any calls are waiting in the queue. If
calls are waiting, we connect an available agent to the next queued
call. Sometimes the next available agent is the same as the agent
whose call is ending. When the agent connects with the queued call, we
update the agent's call object. At this point, we have the data we
need to report correctly on what call the agent is on. But then the
code moves on to the next step in the call end hander, and we clear
out the agent's call and loos the ability to report what cal the agent
is on.

To fix this, we now conditionally clear the agent's call. Before
checking to see if any are waiting in the queue and connecting the
next call, we save away the agent's current call object. If the call
object is the same as before, we clear out the agent's call object,
but if it has changed, we skip clearing out the agent's call object.

### CODE REVIEW

**Comment by terryfinn** [comment]
@benlangfeld @bklang Looks like CI is not running. Anything I can do to help fix it?

**Comment by bklang** [comment]
@terryfinn Travis CI stopped doing builds for open source projects a while back. We need to transition to GitHub actions. Similar work was done in https://github.com/adhearsion/adhearsion/pull/655

**Comment by bklang** [comment]
@terryfinn Do you want to merge this or wait until Github Actions are in place?

**Comment by bklang** [comment]
I can help with this release, and also get you set up to cut future releases.  This project followed [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) workflow, so we would create a temporary release branch, update the version number and CHANGELOG, then merge that to both master and develop. Master would be tagged with the release version, and a gem cut and pushed to Rubygems.

**Comment by nehaabraham** [comment]
@bklang @terryfinn Manually tested calls and everything is in order. We're good to merge this.

**Comment by bklang** [comment]
Sorry, I forgot one request on this PR: please add a note to the top of the CHANGELOG documenting the bug fix. I'll merge as soon as that is in.

**Comment by nehaabraham** [comment]
@bklang @terryfinn Changelog updated

**Comment by bklang** [comment]
Thanks!

**Pull request merged**
